
const PARAMS = {
    DEBUG: false,
    HEX_EDGE_LENGTH: 85,
    WORLD_OFFSET_X: 400,
    WORLD_OFFSET_Y: 60,
    BACKGROUND_COLOUR: '#ffe9ce',
    RIVER_COLOUR: '#0000ff',
    PHASE_X : 500,
    PHASE_Y: 20,
    HOME_MARKER_SIZE: 25
};